### ISSUE TITLE
Headers not working

### ISSUE THREAD

**Issue by bpiec** [webgio/Rotativa#24]
I'm trying to specify headers and footers in a PDF. I saw the answer in issue #13 but it's not working for me.

I have a stylesheet loaded in the meta tag:

``` html
<link href="print.css" rel="stylesheet" type="text/css" media="print" />
```

And in the stylesheet at the bottom:

``` css
@page {
    @top-left {
        content: "TOP SECRET";
        color: red
    }
    @bottom-right {
        content: counter(page);
        font-style: italic
    }
}
```

And then generating PDF by:

``` c#
public ActionResult ShowPdf()
{
  var model = new Model();
  return new ViewAsPdf("view.cshtml", model)
                {
                    FileName = "Report.pdf",
                    CustomSwitches = "--print-media-type"
                };
}
```

And then nothing appears in the header and footer of the PDF. Am I doing something wrong or this is a bug?
